name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Increase Patch Version
        run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=1.0.${{ github.run_number }}

      - name: Build Maven Project
        run: mvn clean install

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app:${{ github.run_number }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/app:${{ github.run_number }} ${{ secrets.DOCKER_USERNAME }}/app:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/app:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/app:latest
